# Welcome to session 3
we will see how can we create matrices using numpy methods

In [7]:
import numpy as np

In [7]:
X = np.zeros((10, 2))
print(X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
X has dimensions: (10, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


In [8]:
X = np.ones((10, 2))
print(X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
X has dimensions: (10, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


#### To create a matrix filled with specific number 

In [10]:
X = np.full((10, 2), 6)
X

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [12]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# Create a diagonal matrix
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

### Create a 10, 2 matrix that has even numbers from 0 to 40

In [23]:
# remember it is the same as range arange(start, end-1, step)
X = np.arange(0, 40, 2)
X.reshape(10, 2)

# OR
X = np.arange(0, 40, 2).reshape(10, 2)
X

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [24]:
X = np.arange(20)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### what if we want non integer values?
np.linspace(start, stop, N)

In [19]:
# 10,2 matrix with non integer elements 
X = np.linspace(0, 10, 20).reshape(10, 2)
X

array([[ 0.        ,  0.52631579],
       [ 1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895],
       [ 3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526],
       [ 7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842],
       [ 9.47368421, 10.        ]])

In [31]:
# another solution
x = np.random.random(10, 2)
x = np.random.random((10, 2))
# Which one is true
x

TypeError: random_sample() takes at most 1 positional argument (2 given)

NumPy also allows us to create ndarrays with random integers within a particular interval. The function np.random.randint(start, stop, size = shape) creates an ndarray of the given shape with random integers in the half-open interval [start, stop)

In [34]:
# solution for the 10,2 matrix with numbers from 0 to 20
X = np.random.randint(0, 20, size = (10, 2))
X

array([[ 1, 13],
       [17, 13],
       [ 7,  1],
       [ 8,  9],
       [ 1, 13],
       [16, 14],
       [13, 15],
       [ 5, 16],
       [14, 14],
       [ 7,  2]])

np.random.normal(mean, standard deviation, size=shape)

In [36]:
X = np.random.normal(0, .2, size= (10, 2))
X

array([[ 0.01113642,  0.081037  ],
       [-0.07862737, -0.33807725],
       [-0.02160165, -0.15808718],
       [-0.17997546, -0.11848183],
       [-0.02976692,  0.15249312],
       [ 0.17427568,  0.31100534],
       [-0.11186583,  0.06839244],
       [-0.09061086,  0.03346055],
       [ 0.14400434, -0.08305994],
       [-0.10159648, -0.01917037]])

### Using the Built-in functions you learned about in the previous lesson, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)


In [39]:
# # solution
# x = np.linspace(2, 32, 16).reshape(4, 4)
# x = np.arange(2, 33, 2).reshape(4, 4)
# x

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

## array are similar to lists

In [52]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original:\n X = \n', X)
print()

# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### drop the first Column and row

In [54]:
X= np.delete(X, [0], axis = 1)
print('X without first row:\n X = \n', X)
X= np.delete(X, [0], axis = 0)
print('X without first col:\n X = \n', X)


X without first row:
 X = 
 [[6]
 [9]]
X without first col:
 X = 
 [[9]]


### SVD and PCA

In [19]:
# Create a (3, 3) matrix  
A = np.arange(0, 9).reshape(3, 3)

U, s, V_t = np.linalg.svd(A)
V = V_t.T
print(U)
print()
print(s)
print()
print(V_t)

[[-0.13511895  0.90281571  0.40824829]
 [-0.49633514  0.29493179 -0.81649658]
 [-0.85755134 -0.31295213  0.40824829]]

[1.42267074e+01 1.26522599e+00 5.89938022e-16]

[[-0.4663281  -0.57099079 -0.67565348]
 [-0.78477477 -0.08545673  0.61386131]
 [-0.40824829  0.81649658 -0.40824829]]


<h1><center>Into to Pandas</center></h1>
<p>Pandas is a package for data manipulation and analysis in Python. The name Pandas is derived from the econometrics term Panel Data. Pandas incorporates two additional data structures into Python, namely Pandas Series and Pandas DataFrame. These data structures allow us to work with labeled and relational data in an easy and intuitive manner.
in this lesson we will focus on loading csv files to apply SVD and PCA </p>

In [55]:
# check that you have pandas libarary 
!conda list pandas

# packages in environment at /home/ahmed/anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    0.24.2           py37he6710b0_0  


<h2><center>Why Pandas</center></h2>
<h5> The recent success of machine learning algorithms is partly because of the huge amounts of data (big data) that we have available to train our algorithms on. Also, manily we need to understand that huge quantity of data and manipulate it </h5>
<br>
1- Easy to load data of different formats into DataFrames
<br>
2- Allows the use of labels for rows and columns
<br>
3- Easy handling of NaN values (non exisiting values)
<br>
4- Can calculate rolling statistics on time series data
<br>
5- Can join and merge different datasets together
<br>
6- It integrates with NumPy and Matplotlib

In [1]:
# We import Pandas as pd into Python
import pandas as pd

In [5]:
# loading our first CSV file
df = pd.read_csv('business.csv')
# show the first 5 rows 
df.head(5)
# this can be a regression problem predicting value which we can cover in the next session with differintiation 

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2018                     Level 1                99999       All industries   
1  2018                     Level 1                99999       All industries   
2  2018                     Level 1                99999       All industries   
3  2018                     Level 1                99999       All industries   
4  2018                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  691859  ANZSIC06 divisions A-S (excluding classes K633...  
1  605766  ANZSIC06 divisions A-S (excluding classes K633...  
2   63509  ANZSIC06 divisions A-S (excluding classes K633...  
3   22583  ANZSIC06 divisions A-S (excluding classes K633...  
4  597623  ANZSIC06 divisions A-S (excluding classes K633...