# How to import the numerical python library

In [3]:
# from numpy import * #import everything, don't use this 
# from numpy import linalg, math
import numpy as np #now I created an instance from numpy called np which i can always use to call any function inside

In [4]:
# how to delete this code cell and get it back

In [5]:
# checking my numpy version because it gets updates as any python package 
!conda list numpy

# packages in environment at /home/ahmed/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.16.2           py37h7e9f1db_0  
numpy-base                1.16.2           py37hde5b4d6_0  
numpydoc                  0.8.0                    py37_0  


### Numpy is an n-dim array object that holdes data from the same type
think of it as a n-dim grid that takes some elements and force all of them to be the same type unlike lists which makes the calc really fast

In [24]:
#with a list
l1 = [1, 2, "ahmed", "mohamed", 10.19]
for i in l1:
    print(type(i))

    

# with arrays
vector = np.array([1, 2, "ahmed", "mohamed", 10.19])
for i in vector:
    print(type(i))
# or 
print("the data type of that array is =", vector.dtype)

<class 'int'>
<class 'int'>
<class 'str'>
<class 'str'>
<class 'float'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
the data type of that array is = <U21


In [10]:
# Lets get the mean of an array of 100000 elements, with python and again with np 
arr = np.random.random(1000000)
import time
start = time.time()
arr_mean = sum(arr) / len(arr)
end = time.time()
print("with list, I used {} s".format(end - start))

with list, I used 0.2563290596008301 s


In [11]:
# let's do it with numpy
start = time.time()
arr_mean = np.mean(arr)
end = time.time()
print("with list, I used {} s".format(end - start))

with list, I used 0.001706838607788086 s


### Let's see one dimentional array

In [25]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
print("data type of the array =", arr.dtype)
print("shape of the array =", arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
data type of the array = int64
shape of the array = (3,)


### Higher dim array (matrices)
A matrix arranges numbers into rows and columns, like this:

\begin{equation}A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
\end{equation}

We refer to the *elements* of the matrix using the lower case equivalent with a subscript row and column indicator, like this:

\begin{equation}A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
\end{equation}

In [45]:
A = np.array([[1, 2, 3],
                [4, 5, 6]], dtype = np.float)
print(A)
print(type(A))
print("shape of the array =", A.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
shape of the array = (2, 3)


### Some Linear Algebra 

#### Adding Matrices

\begin{equation}\begin{bmatrix}1 & 2  \\3 & 4 \end{bmatrix}+ \begin{bmatrix}1 & 2  \\3 & 4\end{bmatrix} = \begin{bmatrix}6 & 8\\ 10 & 12 \end{bmatrix}\end{equation}

#### Subtracting Matrices

\begin{equation}\begin{bmatrix}1 & 2  \\3 & 46\end{bmatrix}- \begin{bmatrix}1 & 2  \\3 & 4\end{bmatrix} = \begin{bmatrix}-4 & -4\\ -4 & -4 \end{bmatrix}\end{equation}

#### Multi Matrices

\begin{equation}\begin{bmatrix}1 & 2  \\3 & 46\end{bmatrix}* \begin{bmatrix}1 & 2  \\3 & 4\end{bmatrix} = \begin{bmatrix}5 & 12\\ 21 & 32 \end{bmatrix}\end{equation}

In [60]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])

# sum
print("Sum of x and y:")
print(x + y)
print(np.add(x, y))
print("\n")

# difference
print("Difference of x - y:")
print(x - y)
print(np.subtract(x, y))
print("\n")

# product
print("Multi x over y:")
print(x * y)
print(np.multiply(x, y))
print("\n")

# division
print("Dividing x over y:")
print(x / y)
print(np.divide(x, y))
print("\n")

# square root
print("the square root of x:")
print(np.sqrt(x))
print("\n")

# negative matrix
print("the inverse of x:")
print(-x)
print("\n")


# Scaling
print("scaling or stetching x by 2:")
print(2 * x)

Sum of x and y:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


Difference of x - y:
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


Multi x over y:
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


Dividing x over y:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


the square root of x:
[[1.         1.41421356]
 [1.73205081 2.        ]]


the inverse of x:
[[-1 -2]
 [-3 -4]]


scaling or stetching x by 2:
[[2 4]
 [6 8]]


In [42]:
# transpose of a matrix
# Note that taking the transpose of a rank 1 array does nothing

print(x)
print(np.transpose(x))
# or
print(x.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[1. 3.]
 [2. 4.]]


In [44]:
# product 

v = np.array([9,10])
w = np.array([11, 12])

# Dot product of vectors
print(v.dot(w))
# or
print(np.dot(v, w))

# Matrix / vector product
print("dot product of a 2*2 matrix by 2*1 vector")
print(np.dot(x, v))

# Matrix / matrix product
print("dot product of a 2*2 matrix by 2*2 matrix")
print(np.dot(x, y))

219
219
dot product of a 2*2 matrix by 2*1 vector
[29. 67.]
dot product of a 2*2 matrix by 2*2 matrix
[[19. 22.]
 [43. 50.]]


They provide many more useful functions like sum of a matrix or an array. You can find all in that <a href = "https://docs.scipy.org/doc/numpy/reference/routines.math.html">documentation</a>

### Introduction to linalg tool 

In [49]:
# norm of a vector 
x = np.array([1, 2])
print(np.linalg.norm(x))

2.23606797749979


#### Solving this system of equations

$$ 3x + y = 9$$ 

$$ x + 2y = 8$$

In [51]:
var = np.array([[3,1], [1,2]])
ans = np.array([9,8])
np.linalg.solve(var, ans)

array([2., 3.])

In [52]:
# the det(matrix)
A= np.array([[1, 2, 3], [2, 3, 5], [4, 5, 6]])
print(np.linalg.det(A))

2.9999999999999996


In [53]:
# getting the inverse of a matrix
print(np.linalg.inv(A))

[[-2.33333333  1.          0.33333333]
 [ 2.66666667 -2.          0.33333333]
 [-0.66666667  1.         -0.33333333]]


In [57]:
# get the Eigen values and Eigen vectors of a matrix
eigen_values, eigen_vectors = np.linalg.eig(A)
print("the EigenValues of the matrix a =\n", eigen_values)
print("the Eigenvectors of the matrix a =\n",
      eigen_vectors)

the EigenValues of the matrix a =
 [11.2662813 -0.2662813 -1.       ]
the Eigenvectors of the matrix a =
 [[-0.33123988 -0.48960855 -0.33333333]
 [-0.54572066  0.80663447 -0.66666667]
 [-0.76972015 -0.3310956   0.66666667]]
